apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sequence-builder
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: sequence-builder
  destinations:
  - name: in-cluster
    namespace: sequence-builder
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/chloeskim-dev/deployment
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sequence-builder
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: '{{.name}}-sequence-builder' # 'name' field of the Secret
    spec:
      project: "sequence-builder"
      source:
        repoURL: https://github.com/chloeskim-dev/deployment
        targetRevision: HEAD
        path: sequence-builder-cd
      destination:
        server: '{{.server}}' # 'server' field of the secret
        namespace: sequence-builder
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
